export { default as Ts } from "./ts.svg" 
export { default as Js } from "./js.svg" 
export { default as Next } from "./nextjs.svg" 
export { default as Anime } from "./icons8-anime-600.svg" 
export {default as Curlybracket} from "./curlybracket.png"
export { default as Aws } from "./aws.svg"
export { default as Cloudflare } from "./cloudflare.svg"
export { default as Docker } from "./docker.svg"
export { default as Framer } from "./framer.png"
export { default as Linux } from "./linux.png"
export { default as MongoDB } from "./mongodb.png"
export { default as React } from "./react.png"
export { default as Postgress } from "./postgress.svg"
export { default as Prisma } from "./prisma.svg"
export { default as Redis } from "./redis.svg"
export { default as Rust } from "./rust.svg"
export { default as solidity } from "./solidity.svg"
export { default as Node } from "./nodejs.svg"
export { default as Python } from "./python.svg"
export { default as Express } from "./express.svg"
export { default as Tailwind } from "./tailwind.svg"
export { default as Kubernetes} from "./kubernetes.svg"
export { default as Gsap} from "./gsap.png"
export { default as Ros} from "./ros.png"
export { default as WebRtc} from "./Rtc.png"
export { default as Cplus} from "./CCplus.png"
export { default as ImageAi } from "./imageai.png"
export { default as GigAi} from  "./gifImageAi.gif"
